name: Build Geode Mod

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          platform: ${{ matrix.config.platform }}
          combine: true

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Combine builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
